# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/jjwhub788/new/blob/main/Untitled3.ipynb
"""

import jax.numpy as jnp

arr = jnp.ones(shape=(5,5))

vec = jnp.array([1, 2, 3, 4, 5])

print(arr @ vec)

hi